### ISSUE TITLE
OsmAnd~ Support

### ISSUE THREAD

**Issue by ghost** [tranquvis/SimpleSmsRemote#17]
I hope I have not misunderstood, but I have read about the google play store that now there is integration with google maps .. well, you could also add an integration for OsmAnd~ (https://f-droid.org/packages/net.osmand.plus/)?

**Comment by tranquvis** [comment]
The message would become very long, if it contains multiple links. 
A good solution would be, to provide an option in the module's settings.
However, there are so much map apps out there and I think the importance of this feature is not very high.

You could also ask OsmAnd~ about that.
OsmAnd~ could support viewing google maps urls.
So you would be able to open all google maps urls with OsmAnd~.

**Comment by protoloo** [comment]
I understood, but I meant to completely replace G Maps with OSM. This is because, in general, one is a proprietary service (and let's say it, also spy), the other is open source and is perhaps the only valid alternative. The global idea would be to use only free services (eg, first of all, Replicant OS.) To which then add apps and infrastructures, so as to progressively exclude those owners.

**Comment by tranquvis** [comment]
Ok. I understand your approach. 

I also prefer using an open source alternative.
But I think in this case, Google maps is much more used than OsmAnd~. 
Probably, if the original issue requested an OsmAnd~ link, I would not have implemented it, because I think it covers too few users.
(Would be happy, if I will be proven wrong.)

**Comment by protoloo** [comment]
If you mean downloads, here they are:

OsmAnd (https://play.google.com/store/apps/details?id=net.osmand)
5.000.000-10.000.000 downloads

OsmAnd+ (https://play.google.com/store/apps/details?id=net.osmand.plus)
100.000-500.000 downloads

They are certainly not as many as G Maps, but they are still many

**Comment by tranquvis** [comment]
I now agree to your opinion. Google Maps should not be preferred over other apps, just because its more used. We should not promote the monopoly even more. However, I would not prefer any specific application, since there are so many out there. Therefore I just removed the google maps link in commit https://github.com/tranquvis/SimpleSmsRemote/commit/0d4b132b92c16f829cc2098d9575457324f648a2.
