### ISSUE TITLE
Enabled location

### ISSUE THREAD

**Issue by miche7** [tranquvis/SimpleSmsRemote#3]
Hello,
And first of all congratulations for this practical application.

Do you know if it is possible to activate the location? Something like "rt enable location".

Also, when I run the "rc get location" command, the program does not wait for gps coordinates (which can sometimes take a little time) and prefers to return "rc-result (failed) get location"

Best regards,

**Comment by tranquvis** [comment]
Hello and thank you for your feedback.

I know this issue.
Enabling gps manually should not be necessary and I think it is not possible to do this without root permissions. However I have reprogrammed the algorithm, which chooses the best location. I also set the maximum wait time (Time, which the app listenes for a new location.) from 4 to 20s.

The updates have been published in version 1.0.1. (on Github and Google Play)
Please let me know, if the problem is solved.

**Comment by lucchinelli** [comment]
Hello.
Also for me congratulations! That is the app that I have searched for. It works very great but I have the save little issues as miche7. 

I installed the app in version 1.0.0 via fdroid. Fist of all: Could you please publish the newest versions also on fdroid?

I use a Honor 4x with 4.4.2 os as the target device. In version 1.0.0 the camera could not be detected. Bad but I don't know why? All other modules are ready. I tested other things and they work well and also the "rc get location" command but it only worked if the I have activated the gps receiver before. Than it works great. If the receiver if off nothing happens. You can activate the gps receiver via a shortcut on a control panel so I don't understand why is it not possible to activate it without root permissions. Can you please check this issure because in normal cases the gps receiver is off to save battery power?

If you need help for testing or mor informations, please let me know this.
Best regards

**Comment by tranquvis** [comment]
Hello lucchinelli,

I'm glad, that you like my application.

It's not possible to activate location services without root since Android 4.4. The control panel as you say obviously has root permissions since it's delivered with android or installed from the manufacturer. You simply should not deactivate the location services. I'm not sure how this behaves in Android 4.4. I don't think it's necessary to deactivate it, since the os handles it quite good to save battery power and you can change the location mode to "Battery saving".

Best regards

**Comment by lucchinelli** [comment]
Hallo Andreas.
Thanks for the (very) quick answer and the detailed explanation. Do you remember my wish with fdroid? And I have a secound one. Can you change the output string for the location from “aa,bbbb,cc,dddd“ to “aa.bbbbb cc.ddddd“ because than it is possible to copy the output directly to google maps or osmand.
Thanks in advance.

**Comment by tranquvis** [comment]
Of course I did not forget.

I plan to publish a new version with bugfixes. (Maybe today) 
During this development I will also take a look on the location format. I will then request fdroid to publish this version.

Thanks for your feedback.

**Comment by tranquvis** [comment]
Version 1.1 is available in Playstore and I have created a Merge Request for FDroid.
https://gitlab.com/fdroid/fdroiddata/merge_requests/2292

**Comment by lucchinelli** [comment]
Hallo Andreas.
      Thanks very much. Today the update on fdroid was available.
      Best Regards
      
      Am 02.06.2017 um 11:12 schrieb Andreas Kaltenleitner:
    
    
      Version 1.1 is available in Playstore and I have created a
        Merge Request for FDroid.
        https://gitlab.com/fdroid/fdroiddata/merge_requests/2292
      —
        You are receiving this because you commented.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tranquvis/SimpleSmsRemote","title":"tranquvis/SimpleSmsRemote","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/tranquvis/SimpleSmsRemote"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tranquvis in #3: Version 1.1 is available in Playstore and I have created a Merge Request for FDroid.\r\nhttps://gitlab.com/fdroid/fdroiddata/merge_requests/2292"}],"action":{"name":"View Issue","url":"https://github.com/tranquvis/SimpleSmsRemote/issues/3#issuecomment-305734022"}}}

**Comment by Bobcadence** [comment]
Hello,
 
I have the same issue than Miche7.
When i use the rc get location commande without use GPS, i get  this :
rc-result
(info) location: 0.0000 0.0000

**Comment by Bobcadence** [comment]
With gps, the command work fine. Strange...
By the way, i started a french traduction ;)

**Comment by cao-** [comment]
"I also set the maximum wait time from 4 to 20s"

I personally think that 20s is too little time for getting the location in some cases, for example when indoor.  When you lose the phone or someone stole it, knowing where it is located is a priority, and according to me it's worth dedicating some more time.  Wouldn't it be better to let the user decide how much time to dedicate to the fix process by using a parameter?  For example:  rc get location 20s

Anyway, thank you for this nice and useful application!

**Comment by tranquvis** [comment]
Many things were discussed here. If you still have problems, please create a new specific issues. I don't know if the wait time is still a problem.
